### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by micsibulo** [HelenFoster/AnkiSpreadsheetImportPlus#3]
Hello. I am not really a coding geek. I'm just med student. I saw this when I imported. Thank you in advance!

Import failed. Debugging info:
Traceback (most recent call last):
  File "aqt\importing.py", line 203, in on_done
  File "concurrent\futures\_base.py", line 432, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
  File "concurrent\futures\thread.py", line 57, in run
  File "anki\importing\noteimp.py", line 81, in run
  File "C:\Users\Admin\AppData\Roaming\Anki2\addons21\716643677\spreadsheet.py", line 45, in foreignNotes
    raise Exception('"Allow HTML in fields" must be checked. Aborting.')
Exception: "Allow HTML in fields" must be checked. Aborting.

**Comment by HelenFoster** [comment]
Hi, in the Anki import dialog, you just need to tick the "Allow HTML in fields" checkbox.

The problem is because I'm reusing the Anki import dialog and there isn't a nice clean way to force that option the right way.
